-- CloudSync PostgreSQL extension upgrade script: 1.0 -> 1.0.17
--
-- Existing deployments installed under the static 1.0 default_version need a
-- valid upgrade path to reach 1.0.17, the first release to track
-- CLOUDSYNC_VERSION from src/cloudsync.h as the extension version.
--
-- No SQL-level changes were introduced between 1.0 and 1.0.17 -- the install
-- script surface is identical. This file exists solely to advertise a valid
-- upgrade path so users can run:
--
--     ALTER EXTENSION cloudsync UPDATE;
--
-- instead of the destructive DROP EXTENSION ... CASCADE; CREATE EXTENSION ...
-- workaround.
