{
 "title": "CloudSync",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "action",
    "label": "Action",
    "query": "SELECT DISTINCT action\nFROM cloudsync_metrics\nORDER BY action;"
   },
   { "name": "ProjectID", "label": "ProjectID" },
   { "name": "SiteID" }
  ]
 },
 "panels": [
  {
   "title": "Activity (distinct devices)",
   "type": "timeseries",
   "description": "N. of distinct devices which made at least one request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  $__unixEpochGroup(created_at, '1h') AS time,\n  COUNT(DISTINCT project_id || '/' || database || '/' || site_id) AS devices\nFROM cloudsync_metrics\nWHERE $__unixEpochFilter(created_at)\n  AND ('${ProjectID}' = '' OR project_id ~ '${ProjectID}')\n  AND ('${SiteID}' = '' OR site_id ~ '${SiteID}')\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Total Activity",
   "type": "timeseries",
   "description": "Total number of requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  $__unixEpochGroup(created_at, '1h') AS time,\n  COUNT(*) AS requests\nFROM cloudsync_metrics\nWHERE $__unixEpochFilter(created_at)\n  AND ('${ProjectID}' = '' OR project_id ~ '${ProjectID}')\n  AND ('${SiteID}' = '' OR site_id ~ '${SiteID}')\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Traffic MB (In+Out)",
   "type": "timeseries",
   "description": "Total amount of traffic in MB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  $__unixEpochGroup(created_at, '1h') AS time,\n  SUM(bytes_in + bytes_out) / 1024 / 1024 AS megabytes\nFROM cloudsync_metrics\nWHERE $__unixEpochFilter(created_at)\n  AND ('${ProjectID}' = '' OR project_id ~ '${ProjectID}')\n  AND ('${SiteID}' = '' OR site_id ~ '${SiteID}')\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Traffic MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  $__unixEpochGroup(created_at, '1h') AS time,\n  action,\n  SUM(bytes_in + bytes_out) / 1024 / 1024 AS megabytes\nFROM cloudsync_metrics\nWHERE $__unixEpochFilter(created_at)\n  AND action ~ '${action:regex}'\n  AND ('${ProjectID}' = '' OR project_id ~ '${ProjectID}')\n  AND ('${SiteID}' = '' OR site_id ~ '${SiteID}')\nGROUP BY 1, 2\nORDER BY 1;\n"
    }
   ]
  }
 ]
}