name: sqlite_sync
version: 0.8.64
description: >
  SQLite Sync is a multi-platform extension that brings a true local-first
  experience to your applications with minimal effort. It extends standard
  SQLite tables with built-in support for offline work and automatic
  synchronization, allowing multiple devices to operate independently—even
  without a network connection—and seamlessly stay in sync.
homepage: https://github.com/sqliteai/sqlite-sync
repository: https://github.com/sqliteai/sqlite-sync

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: ^1.0.0
  hooks: ^1.0.0
  path: ^1.8.0
  sqlite3: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
